name: PulseEvents
version: 0.0.3
main: com.voidpulse.pulseevents.PulseEvents
api-version: 1.20

commands:
  pe:
    description: Main command
    usage: /pe
    permission: pulseevents.admin

permissions:
  pulseevents.admin:
    description: Access to admin features
    default: op